[project]
name = "nestargs"
version = "0.0.0.dev0"
description = "Nested arguments parser"
authors = [{ name = "Takahiro Yano", email = "speg03@gmail.com" }]

readme = "README.md"
license = "MIT"

requires-python = ">=3.10"
keywords = ["argparse", "arguments", "cli", "command", "interface", "line", "parser"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.urls]
Repository = "https://github.com/speg03/nestargs"

[dependency-groups]
dev = [
  { include-group = "tests" },
]
tests = [
  "pre-commit>=4.6.1",
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "--cov=nestargs --cov-report=term-missing --cov-report=xml"
