name: Python Tests

on:
  pull_request:
  workflow_call:

concurrency:
  group: python-tests-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v7
      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: make install
      - name: Test with python ${{ matrix.python-version }}
        run: make test
      - name: Upload coverage reports
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        if: env.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v7
