name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: dschep/install-poetry-action@v1.3

    - name: Build
      run: poetry build

    - name: Publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish

  update-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: actions/setup-python@v1
    - uses: dschep/install-poetry-action@v1.3

    - name: Update development version
      id: changes
      run: |
        poetry version prerelease
        git status -s
        git add ./pyproject.toml
        echo "::set-output name=next_version::$(poetry version | awk '{print $2}')"

    - name: Commit changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git commit -m ":construction: Update development version to ${{ steps.changes.outputs.next_version }}"
        git push origin master
